// src/app/(themed)/admin/dashboard/DashBoardComponents/AddMessage/QuranData.tsx
'use client';

export interface SurahInfo {
  no: string;
  english: string;
  arabic: string;
  totalAyahs: number;
}

export const SURAH_LIST: SurahInfo[] = [
  { no: '1',   english: 'Al-Fatihah',       arabic: 'الفاتحة',     totalAyahs: 7 },
  { no: '2',   english: 'Al-Baqarah',       arabic: 'البقرة',       totalAyahs: 286 },
  { no: '3',   english: 'Ali `Imran',       arabic: 'آل عمران',     totalAyahs: 200 },
  { no: '4',   english: 'An-Nisa`',         arabic: 'النساء',       totalAyahs: 176 },
  { no: '5',   english: 'Al-Ma`idah',       arabic: 'المائدة',     totalAyahs: 120 },
  { no: '6',   english: 'Al-An`am',         arabic: 'الأنعام',     totalAyahs: 165 },
  { no: '7',   english: 'Al-A`raf',         arabic: 'الأعراف',     totalAyahs: 206 },
  { no: '8',   english: 'Al-Anfal',         arabic: 'الأنفال',     totalAyahs: 75 },
  { no: '9',   english: 'At-Tawbah',        arabic: 'التوبة',       totalAyahs: 129 },
  { no: '10',  english: 'Yunus',            arabic: 'يونس',       totalAyahs: 109 },
  { no: '11',  english: 'Hud',              arabic: 'هود',        totalAyahs: 123 },
  { no: '12',  english: 'Yusuf',            arabic: 'يوسف',       totalAyahs: 111 },
  { no: '13',  english: 'Ar-Ra`d',          arabic: 'الرعد',       totalAyahs: 43 },
  { no: '14',  english: 'Ibrahim',          arabic: 'إبراهيم',     totalAyahs: 52 },
  { no: '15',  english: 'Al-Hijr',          arabic: 'الحجر',       totalAyahs: 99 },
  { no: '16',  english: 'An-Nahl',          arabic: 'النحل',       totalAyahs: 128 },
  { no: '17',  english: 'Al-Isra`',         arabic: 'الإسراء',     totalAyahs: 111 },
  { no: '18',  english: 'Al-Kahf',          arabic: 'الكهف',       totalAyahs: 110 },
  { no: '19',  english: 'Maryam',           arabic: 'مريم',        totalAyahs: 98 },
  { no: '20',  english: 'Ta-Ha',            arabic: 'طه',          totalAyahs: 135 },
  { no: '21',  english: 'Al-Anbiya`',       arabic: 'الأنبياء',     totalAyahs: 112 },
  { no: '22',  english: 'Al-Hajj',          arabic: 'الحج',         totalAyahs: 78 },
  { no: '23',  english: 'Al-Mu`minun',      arabic: 'المؤمنون',     totalAyahs: 118 },
  { no: '24',  english: 'An-Nur',           arabic: 'النور',        totalAyahs: 64 },
  { no: '25',  english: 'Al-Furqan',        arabic: 'الفرقان',     totalAyahs: 77 },
  { no: '26',  english: 'Ash-Shu`ara`',     arabic: 'الشعراء',     totalAyahs: 227 },
  { no: '27',  english: 'An-Naml',          arabic: 'النمل',        totalAyahs: 93 },
  { no: '28',  english: 'Al-Qasas',         arabic: 'القصص',       totalAyahs: 88 },
  { no: '29',  english: 'Al-`Ankabut',      arabic: 'العنكبوت',     totalAyahs: 69 },
  { no: '30',  english: 'Ar-Rum',           arabic: 'الروم',       totalAyahs: 60 },
  { no: '31',  english: 'Luqman',           arabic: 'لقمان',        totalAyahs: 34 },
  { no: '32',  english: 'As-Sajdah',        arabic: 'السجدة',       totalAyahs: 30 },
  { no: '33',  english: 'Al-Ahzab',         arabic: 'الأحزاب',      totalAyahs: 73 },
  { no: '34',  english: 'Saba`',            arabic: 'سبأ',          totalAyahs: 54 },
  { no: '35',  english: 'Fatir',            arabic: 'فاطر',         totalAyahs: 45 },
  { no: '36',  english: 'Ya-Sin',           arabic: 'يس',           totalAyahs: 83 },
  { no: '37',  english: 'As-Saffat',        arabic: 'الصافات',      totalAyahs: 182 },
  { no: '38',  english: 'Sad',              arabic: 'ص',            totalAyahs: 88 },
  { no: '39',  english: 'Az-Zumar',         arabic: 'الزمر',        totalAyahs: 75 },
  { no: '40',  english: 'Ghafir',           arabic: 'غافر',         totalAyahs: 85 },
  { no: '41',  english: 'Fussilat',         arabic: 'فصلت',         totalAyahs: 54 },
  { no: '42',  english: 'Ash-Shura',        arabic: 'الشورى',       totalAyahs: 53 },
  { no: '43',  english: 'Az-Zukhruf',       arabic: 'الزخرف',       totalAyahs: 89 },
  { no: '44',  english: 'Ad-Dukhan',        arabic: 'الدخان',       totalAyahs: 59 },
  { no: '45',  english: 'Al-Jathiyah',      arabic: 'الجاثية',      totalAyahs: 37 },
  { no: '46',  english: 'Al-Ahqaf',         arabic: 'الأحقاف',      totalAyahs: 35 },
  { no: '47',  english: 'Muhammad',         arabic: 'محمد',         totalAyahs: 38 },
  { no: '48',  english: 'Al-Fath',          arabic: 'الفتح',        totalAyahs: 29 },
  { no: '49',  english: 'Al-Hujurat',       arabic: 'الحجرات',      totalAyahs: 18 },
  { no: '50',  english: 'Qaf',              arabic: 'ق',            totalAyahs: 45 },
  { no: '51',  english: 'Adh-Dhariyat',     arabic: 'الذاريات',     totalAyahs: 60 },
  { no: '52',  english: 'At-Tur',           arabic: 'الطور',         totalAyahs: 49 },
  { no: '53',  english: 'An-Najm',          arabic: 'النجم',        totalAyahs: 62 },
  { no: '54',  english: 'Al-Qamar',         arabic: 'القمر',        totalAyahs: 55 },
  { no: '55',  english: 'Ar-Rahman',        arabic: 'الرحمن',       totalAyahs: 78 },
  { no: '56',  english: 'Al-Waqi`ah',       arabic: 'الواقعة',      totalAyahs: 96 },
  { no: '57',  english: 'Al-Hadid',         arabic: 'الحديد',       totalAyahs: 29 },
  { no: '58',  english: 'Al-Mujadilah',     arabic: 'المجادلة',     totalAyahs: 22 },
  { no: '59',  english: 'Al-Hashr',         arabic: 'الحشر',        totalAyahs: 24 },
  { no: '60',  english: 'Al-Mumtahanah',    arabic: 'الممتحنة',     totalAyahs: 13 },
  { no: '61',  english: 'As-Saff',          arabic: 'الصف',         totalAyahs: 14 },
  { no: '62',  english: 'Al-Jumu`ah',       arabic: 'الجمعة',       totalAyahs: 11 },
  { no: '63',  english: 'Al-Munafiqun',     arabic: 'المنافقون',     totalAyahs: 11 },
  { no: '64',  english: 'At-Taghabun',      arabic: 'التغابن',      totalAyahs: 18 },
  { no: '65',  english: 'At-Talaq',         arabic: 'الطلاق',       totalAyahs: 12 },
  { no: '66',  english: 'At-Tahrim',        arabic: 'التحريم',      totalAyahs: 12 },
  { no: '67',  english: 'Al-Mulk',          arabic: 'الملك',        totalAyahs: 30 },
  { no: '68',  english: 'Al-Qalam',         arabic: 'القلم',        totalAyahs: 52 },
  { no: '69',  english: 'Al-Haqqah',        arabic: 'الحاقة',       totalAyahs: 52 },
  { no: '70',  english: 'Al-Ma`arij',       arabic: 'المعارج',      totalAyahs: 44 },
  { no: '71',  english: 'Nuh',              arabic: 'نوح',          totalAyahs: 28 },
  { no: '72',  english: 'Al-Jinn',          arabic: 'الجن',         totalAyahs: 28 },
  { no: '73',  english: 'Al-Muzzammil',     arabic: 'المزمل',       totalAyahs: 20 },
  { no: '74',  english: 'Al-Muddaththir',   arabic: 'المدثر',       totalAyahs: 56 },
  { no: '75',  english: 'Al-Qiyamah',       arabic: 'القيامة',      totalAyahs: 40 },
  { no: '76',  english: 'Al-Insan',         arabic: 'الإنسان',      totalAyahs: 31 },
  { no: '77',  english: 'Al-Mursalat',      arabic: 'المرسلات',     totalAyahs: 50 },
  { no: '78',  english: 'An-Naba`',         arabic: 'النبأ',        totalAyahs: 40 },
  { no: '79',  english: 'An-Nazi`at',       arabic: 'النازعات',     totalAyahs: 46 },
  { no: '80',  english: '`Abasa',           arabic: 'عبس',         totalAyahs: 42 },
  { no: '81',  english: 'At-Takwir',        arabic: 'التكوير',      totalAyahs: 29 },
  { no: '82',  english: 'Al-Infitar',       arabic: 'الإنفطار',     totalAyahs: 19 },
  { no: '83',  english: 'Al-Mutaffifin',    arabic: 'المطففين',     totalAyahs: 36 },
  { no: '84',  english: 'Al-Inshiqaq',      arabic: 'الإنشقاق',     totalAyahs: 25 },
  { no: '85',  english: 'Al-Buruj',         arabic: 'البروج',       totalAyahs: 22 },
  { no: '86',  english: 'At-Tariq',         arabic: 'الطارق',       totalAyahs: 17 },
  { no: '87',  english: 'Al-A`la',          arabic: 'الأعلى',       totalAyahs: 19 },
  { no: '88',  english: 'Al-Ghashiyah',     arabic: 'الغاشية',      totalAyahs: 26 },
  { no: '89',  english: 'Al-Fajr',          arabic: 'الفجر',        totalAyahs: 30 },
  { no: '90',  english: 'Al-Balad',         arabic: 'البلد',        totalAyahs: 20 },
  { no: '91',  english: 'Ash-Shams',        arabic: 'الشمس',        totalAyahs: 15 },
  { no: '92',  english: 'Al-Layl',          arabic: 'الليل',        totalAyahs: 21 },
  { no: '93',  english: 'Ad-Duhaa',         arabic: 'الضحى',        totalAyahs: 11 },
  { no: '94',  english: 'Ash-Sharh',        arabic: 'الشرح',        totalAyahs: 8 },
  { no: '95',  english: 'At-Tin',           arabic: 'التين',        totalAyahs: 8 },
  { no: '96',  english: 'Al-`Alaq',         arabic: 'العلق',        totalAyahs: 19 },
  { no: '97',  english: 'Al-Qadr',          arabic: 'القدر',        totalAyahs: 5 },
  { no: '98',  english: 'Al-Bayyinah',      arabic: 'البينة',       totalAyahs: 8 },
  { no: '99',  english: 'Az-Zalzalah',      arabic: 'الزلزلة',       totalAyahs: 8 },
  { no: '100', english: 'Al-`Adiyat',       arabic: 'العاديات',     totalAyahs: 11 },
  { no: '101', english: 'Al-Qari`ah',       arabic: 'القارعة',       totalAyahs: 11 },
  { no: '102', english: 'At-Takathur',      arabic: 'التكاثر',      totalAyahs: 8 },
  { no: '103', english: 'Al-`Asr',          arabic: 'العصر',        totalAyahs: 3 },
  { no: '104', english: 'Al-Humazah',       arabic: 'الهمزة',        totalAyahs: 9 },
  { no: '105', english: 'Al-Fil',           arabic: 'الفيل',        totalAyahs: 5 },
  { no: '106', english: 'Quraysh',          arabic: 'قريش',         totalAyahs: 4 },
  { no: '107', english: 'Al-Ma`un',         arabic: 'الماعون',      totalAyahs: 7 },
  { no: '108', english: 'Al-Kawthar',       arabic: 'الكوثر',       totalAyahs: 3 },
  { no: '109', english: 'Al-Kafirun',       arabic: 'الكافرون',     totalAyahs: 6 },
  { no: '110', english: 'An-Nasr',          arabic: 'النصر',        totalAyahs: 3 },
  { no: '111', english: 'Al-Masad',         arabic: 'المسد',        totalAyahs: 5 },
  { no: '112', english: 'Al-Ikhlas',        arabic: 'الإخلاص',       totalAyahs: 4 },
  { no: '113', english: 'Al-Falaq',         arabic: 'الفلق',        totalAyahs: 5 },
  { no: '114', english: 'An-Nas',           arabic: 'الناس',        totalAyahs: 6 },
];
